name: Deploy static content to Pages

on:
  push:
    branches:
      - main  # Cambia esto si usas una rama diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Esto apunta a la raíz, donde está tu index.html
